name: build
on:
  - push
jobs:
  my-job:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: oven-sh/setup-bun@v1
      - run: |
          bun install
          bun run build
