name: lint-and-fix
on:
  - push
jobs:
  my-job:
    name: Run Lint and Fix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: oven-sh/setup-bun@v1
      - run: |
          bun install
          bun run lintAndFix
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Ran lintAndFix."
          git push
